clean: ## Clean autogenerated files
	rm -rf dist
	rm -f .coverage
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(pycache|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	find . | grep -E ".ruff_cache" | xargs rm -rf
	find . | grep -E ".Trash-0" | xargs rm -rf
